# coding=utf-8

#FIXME: Make these utilities so implementations can modify error messages as needed

response_codes = {
1: 'Approved',
2: 'Declined',
3: 'Error',
4: 'Held for Review',
}

reason_codes = {
1: {'response_code': 1, 'reason_code': 1, 'text': "This transaction has been approved.", 'details': " "},
2: {'response_code': 2, 'reason_code': 2, 'text': "This transaction has been declined.", 'details': " "},
3: {'response_code': 2, 'reason_code': 3, 'text': "This transaction has been declined.", 'details': " "},
4: {'response_code': 2, 'reason_code': 4, 'text': "This transaction has been declined.", 'details': "The code returned from the processor indicating that the card used needs to be picked up."},
5: {'response_code': 3, 'reason_code': 5, 'text': "A valid amount is required.", 'details': "The value submitted in the amount field did not pass validation for a number."},
6: {'response_code': 3, 'reason_code': 6, 'text': "The credit card number is invalid.", 'details': " "},
7: {'response_code': 3, 'reason_code': 7, 'text': "The credit card expiration date is invalid.", 'details': "The format of the date submitted was incorrect."},
8: {'response_code': 3, 'reason_code': 8, 'text': "The credit card has expired.", 'details': " "},
9: {'response_code': 3, 'reason_code': 9, 'text': "The ABA code is invalid.", 'details': "The value submitted in the x_bank_aba_code field did not pass validation or was not for a valid financial institution."},
10: {'response_code': 3, 'reason_code': 10, 'text': "The account number is invalid.", 'details': "The value submitted in the x_bank_acct_num field did not pass validation."},
11: {'response_code': 3, 'reason_code': 11, 'text': "A duplicate transaction has been submitted.", 'details': "A transaction with identical amount and credit card information was submitted two minutes prior."},
12: {'response_code': 3, 'reason_code': 12, 'text': "An authorization code is required but not present.", 'details': "A transaction that required x_auth_code to be present was submitted without a value."},
13: {'response_code': 3, 'reason_code': 13, 'text': "The merchant API Login ID is invalid or the account is inactive.", 'details': " "},
14: {'response_code': 3, 'reason_code': 14, 'text': "The Referrer or Relay Response URL is invalid.", 'details': "The Relay Response or Referrer URL does not match the merchants configured value(s) or is absent. Applicable only to SIM and WebLink APIs."},
15: {'response_code': 3, 'reason_code': 15, 'text': "The transaction ID is invalid.", 'details': "The transaction ID value is non-numeric or was not present for a transaction that requires it (i.e., VOID, PRIOR_AUTH_CAPTURE, and CREDIT)."},
16: {'response_code': 3, 'reason_code': 16, 'text': "The transaction was not found.", 'details': "The transaction ID sent in was properly formatted but the gateway had no record of the transaction."},
17: {'response_code': 3, 'reason_code': 17, 'text': "The merchant does not accept this type of credit card.", 'details': "The merchant was not configured to accept the credit card submitted in the transaction."},
18: {'response_code': 3, 'reason_code': 18, 'text': "ACH transactions are not accepted by this merchant.", 'details': "The merchant does not accept electronic checks."},
19: {'response_code': 3, 'reason_code': 19, 'text': "An error occurred during processing. Please try again in 5 minutes.", 'details': " "},
20: {'response_code': 3, 'reason_code': 20, 'text': "An error occurred during processing. Please try again in 5 minutes.", 'details': " "},
21: {'response_code': 3, 'reason_code': 21, 'text': "An error occurred during processing. Please try again in 5 minutes.", 'details': " "},
22: {'response_code': 3, 'reason_code': 22, 'text': "An error occurred during processing. Please try again in 5 minutes.", 'details': " "},
23: {'response_code': 3, 'reason_code': 23, 'text': "An error occurred during processing. Please try again in 5 minutes.", 'details': " "},
24: {'response_code': 3, 'reason_code': 24, 'text': "The Nova Bank Number or Terminal ID is incorrect. Call Merchant Service Provider.", 'details': " "},
25: {'response_code': 3, 'reason_code': 25, 'text': "An error occurred during processing. Please try again in 5 minutes.", 'details': " "},
26: {'response_code': 3, 'reason_code': 26, 'text': "An error occurred during processing. Please try again in 5 minutes.", 'details': " "},
27: {'response_code': 2, 'reason_code': 27, 'text': "The transaction resulted in an AVS mismatch. The address provided does not match billing address of cardholder.", 'details': " "},
28: {'response_code': 2, 'reason_code': 28, 'text': "The merchant does not accept this type of credit card.", 'details': "The Merchant ID at the processor was not configured to accept this card type."},
29: {'response_code': 2, 'reason_code': 29, 'text': "The Paymentech identification numbers are incorrect. Call Merchant Service Provider.", 'details': " "},
30: {'response_code': 2, 'reason_code': 30, 'text': "The configuration with the processor is invalid. Call Merchant Service Provider.", 'details': " "},
31: {'response_code': 2, 'reason_code': 31, 'text': "The FDC Merchant ID or Terminal ID is incorrect. Call Merchant Service Provider.", 'details': "The merchant was incorrectly set up at the processor."},
32: {'response_code': 3, 'reason_code': 32, 'text': "This reason code is reserved or not applicable to this API.", 'details': " "},
#33: {'response_code': 3, 'reason_code': 33, 'text': "FIELD cannot be left blank.", 'details': "The word FIELD will be replaced by an actual field name. This error indicates that a field the merchant specified as required was not filled in."},
# NOTE: Override the authnet provided text since we will only receive the id and need to construct a meaningful message to display to the user
33: {'response_code': 3, 'reason_code': 33, 'text': "Required field cannot be left blank.", 'details': "The word FIELD will be replaced by an actual field name. This error indicates that a field the merchant specified as required was not filled in."},
34: {'response_code': 2, 'reason_code': 34, 'text': "The VITAL identification numbers are incorrect. Call Merchant Service Provider.", 'details': "The merchant was incorrectly set up at the processor."},
35: {'response_code': 2, 'reason_code': 35, 'text': "An error occurred during processing. Call Merchant Service Provider.", 'details': "The merchant was incorrectly set up at the processor."},
36: {'response_code': 3, 'reason_code': 36, 'text': "The authorization was approved, but settlement failed.", 'details': " "},
37: {'response_code': 2, 'reason_code': 37, 'text': "The credit card number is invalid.", 'details': " "},
38: {'response_code': 2, 'reason_code': 38, 'text': "The Global Payment System identification numbers are incorrect. Call Merchant Service Provider.", 'details': "The merchant was incorrectly set up at the processor."},
40: {'response_code': 3, 'reason_code': 40, 'text': "This transaction must be encrypted.", 'details': " "},
41: {'response_code': 2, 'reason_code': 41, 'text': "This transaction has been declined.", 'details': "Only merchants set up for the FraudScreen.Net service would receive this decline. This code will be returned if a given transactions fraud score is higher than the threshold set by the merchant."},
43: {'response_code': 3, 'reason_code': 43, 'text': "The merchant was incorrectly set up at the processor. Call your Merchant Service Provider.", 'details': "The merchant was incorrectly set up at the processor."},
44: {'response_code': 2, 'reason_code': 44, 'text': "This transaction has been declined.", 'details': "The card code submitted with the transaction did not match the card code on file at the card issuing bank and the transaction was declined"},
45: {'response_code': 2, 'reason_code': 45, 'text': "This transaction has been declined.", 'details': "This error would be returned if the transaction received a code from the processor that matched the rejection criteria set by the merchant for both the AVS and Card Code filters."},
46: {'response_code': 3, 'reason_code': 46, 'text': "Your session has expired or does not exist. You must log in to continue working.", 'details': " "},
47: {'response_code': 3, 'reason_code': 47, 'text': "The amount requested for settlement may not be greater than the original amount authorized.", 'details': "This occurs if the merchant tries to capture funds greater than the amount of the original authorization-only transaction."},
48: {'response_code': 3, 'reason_code': 48, 'text': "This processor does not accept partial reversals.", 'details': "The merchant attempted to settle for less than the originally authorized amount."},
49: {'response_code': 3, 'reason_code': 49, 'text': "A transaction amount greater than $[amount] will not be accepted.", 'details': "The transaction amount submitted was greater than the maximum amount allowed."},
50: {'response_code': 3, 'reason_code': 50, 'text': "This transaction is awaiting settlement and cannot be refunded.", 'details': "Credits or refunds may only be performed against settled transactions. The transaction against which the credit/refund was submitted has not been settled, so a credit cannot be issued."},
51: {'response_code': 3, 'reason_code': 51, 'text': "The sum of all credits against this transaction is greater than the original transaction amount.", 'details': " "},
52: {'response_code': 3, 'reason_code': 52, 'text': "The transaction was authorized, but the client could not be notified; the transaction will not be settled.", 'details': " "},
53: {'response_code': 3, 'reason_code': 53, 'text': "The transaction type was invalid for ACH transactions.", 'details': "If x_method = ECHECK, x_type cannot be set to CAPTURE_ONLY."},
54: {'response_code': 3, 'reason_code': 54, 'text': "The referenced transaction does not meet the criteria for issuing a credit.", 'details': " "},
55: {'response_code': 3, 'reason_code': 55, 'text': "The sum of credits against the referenced transaction would exceed the original debit amount.", 'details': "The transaction is rejected if the sum of this credit and prior credits exceeds the original debit amount"},
56: {'response_code': 3, 'reason_code': 56, 'text': "This merchant accepts ACH transactions only; no credit card transactions are accepted.", 'details': "The merchant processes eCheck.Net transactions only and does not accept credit cards."},
57: {'response_code': 3, 'reason_code': 57, 'text': "An error occurred in processing. Please try again in 5 minutes.", 'details': " "},
58: {'response_code': 3, 'reason_code': 58, 'text': "An error occurred in processing. Please try again in 5 minutes.", 'details': " "},
59: {'response_code': 3, 'reason_code': 59, 'text': "An error occurred in processing. Please try again in 5 minutes.", 'details': " "},
60: {'response_code': 3, 'reason_code': 60, 'text': "An error occurred in processing. Please try again in 5 minutes.", 'details': " "},
61: {'response_code': 3, 'reason_code': 61, 'text': "An error occurred in processing. Please try again in 5 minutes.", 'details': " "},
62: {'response_code': 3, 'reason_code': 62, 'text': "An error occurred in processing. Please try again in 5 minutes.", 'details': " "},
63: {'response_code': 3, 'reason_code': 63, 'text': "An error occurred in processing. Please try again in 5 minutes.", 'details': " "},
65: {'response_code': 2, 'reason_code': 65, 'text': "This transaction has been declined.", 'details': "The transaction was declined because the merchant configured their account through the Merchant Interface to reject transactions with certain values for a Card Code mismatch."},
66: {'response_code': 3, 'reason_code': 66, 'text': "This transaction cannot be accepted for processing.", 'details': "The transaction did not meet gateway security guidelines."},
68: {'response_code': 3, 'reason_code': 68, 'text': "The version parameter is invalid.", 'details': "The value submitted in x_version was invalid."},
69: {'response_code': 3, 'reason_code': 69, 'text': "The transaction type is invalid.", 'details': "The value submitted in x_type was invalid."},
70: {'response_code': 3, 'reason_code': 70, 'text': "The transaction method is invalid.", 'details': "The value submitted in x_method was invalid."},
71: {'response_code': 3, 'reason_code': 71, 'text': "The bank account type is invalid.", 'details': "The value submitted in x_bank_acct_type was invalid."},
72: {'response_code': 3, 'reason_code': 72, 'text': "The authorization code is invalid.", 'details': "The value submitted in x_auth_code was more than six characters in length."},
73: {'response_code': 3, 'reason_code': 73, 'text': "The drivers license date of birth is invalid.", 'details': "The format of the value submitted in x_drivers_license_dob was invalid."},
74: {'response_code': 3, 'reason_code': 74, 'text': "The duty amount is invalid.", 'details': "The value submitted in x_duty failed format validation."},
75: {'response_code': 3, 'reason_code': 75, 'text': "The freight amount is invalid.", 'details': "The value submitted in x_freight failed format validation."},
76: {'response_code': 3, 'reason_code': 76, 'text': "The tax amount is invalid.", 'details': "The value submitted in x_tax failed format validation."},
77: {'response_code': 3, 'reason_code': 77, 'text': "The SSN or tax ID is invalid.", 'details': "The value submitted in x_customer_tax_id failed validation."},
78: {'response_code': 3, 'reason_code': 78, 'text': "The Card Code (CVV2/CVC2/CID) is invalid.", 'details': "The value submitted in x_card_code failed format validation."},
79: {'response_code': 3, 'reason_code': 79, 'text': "The drivers license number is invalid.", 'details': "The value submitted in x_drivers_license_num failed format validation."},
80: {'response_code': 3, 'reason_code': 80, 'text': "The drivers license state is invalid.", 'details': "The value submitted in x_drivers_license_state failed format validation."},
81: {'response_code': 3, 'reason_code': 81, 'text': "The requested form type is invalid.", 'details': "The merchant requested an integration method not compatible with the AIM API."},
82: {'response_code': 3, 'reason_code': 82, 'text': "Scripts are only supported in version 2.5.", 'details': "The system no longer supports version 2.5; requests cannot be posted to scripts."},
83: {'response_code': 3, 'reason_code': 83, 'text': "The requested script is either invalid or no longer supported.", 'details': "The system no longer supports version 2.5; requests cannot be posted to scripts."},
84: {'response_code': 3, 'reason_code': 84, 'text': "This reason code is reserved or not applicable to this API.", 'details': " "},
85: {'response_code': 3, 'reason_code': 85, 'text': "This reason code is reserved or not applicable to this API.", 'details': " "},
86: {'response_code': 3, 'reason_code': 86, 'text': "This reason code is reserved or not applicable to this API.", 'details': " "},
87: {'response_code': 3, 'reason_code': 87, 'text': "This reason code is reserved or not applicable to this API.", 'details': " "},
88: {'response_code': 3, 'reason_code': 88, 'text': "This reason code is reserved or not applicable to this API.", 'details': " "},
89: {'response_code': 3, 'reason_code': 89, 'text': "This reason code is reserved or not applicable to this API.", 'details': " "},
90: {'response_code': 3, 'reason_code': 90, 'text': "This reason code is reserved or not applicable to this API.", 'details': " "},
91: {'response_code': 3, 'reason_code': 91, 'text': "Version 2.5 is no longer supported.", 'details': " "},
92: {'response_code': 3, 'reason_code': 92, 'text': "The gateway no longer supports the requested method of integration.", 'details': " "},
97: {'response_code': 3, 'reason_code': 97, 'text': "This transaction cannot be accepted.", 'details': "Applicable only to SIM API. Fingerprints are only valid for a short period of time. This code indicates that the transaction fingerprint has expired."},
98: {'response_code': 3, 'reason_code': 98, 'text': "This transaction cannot be accepted.", 'details': "Applicable only to SIM API. The transaction fingerprint has already been used."},
99: {'response_code': 3, 'reason_code': 99, 'text': "This transaction cannot be accepted.", 'details': "Applicable only to SIM API. The server-generated fingerprint does not match the merchant-specified fingerprint in the x_fp_hash field."},
100: {'response_code': 3, 'reason_code': 100, 'text': "The eCheck.Net type is invalid.", 'details': "Applicable only to eCheck.Net. The value specified in the x_echeck_type field is invalid."},
101: {'response_code': 3, 'reason_code': 101, 'text': "The given name on the account and/or the account type does not match the actual account.", 'details': "Applicable only to eCheck.Net. The specified name on the account and/or the account type do not match the NOC record for this account."},
102: {'response_code': 3, 'reason_code': 102, 'text': "This request cannot be accepted.", 'details': "A password or Transaction Key was submitted with this WebLink request. This is a high security risk."},
103: {'response_code': 3, 'reason_code': 103, 'text': "This transaction cannot be accepted.", 'details': "A valid fingerprint, Transaction Key, or password is required for this transaction."},
104: {'response_code': 3, 'reason_code': 104, 'text': "This transaction is currently under review.", 'details': "Applicable only to eCheck.Net. The value submitted for country failed validation."},
105: {'response_code': 3, 'reason_code': 105, 'text': "This transaction is currently under review.", 'details': "Applicable only to eCheck.Net. The values submitted for city and country failed validation."},
106: {'response_code': 3, 'reason_code': 106, 'text': "This transaction is currently under review.", 'details': "Applicable only to eCheck.Net. The value submitted for company failed validation."},
107: {'response_code': 3, 'reason_code': 107, 'text': "This transaction is currently under review.", 'details': "Applicable only to eCheck.Net. The value submitted for bank account name failed validation."},
108: {'response_code': 3, 'reason_code': 108, 'text': "This transaction is currently under review.", 'details': "Applicable only to eCheck.Net. The values submitted for first name and last name failed validation."},
109: {'response_code': 3, 'reason_code': 109, 'text': "This transaction is currently under review.", 'details': "Applicable only to eCheck.Net. The values submitted for first name and last name failed validation."},
110: {'response_code': 3, 'reason_code': 110, 'text': "This transaction is currently under review.", 'details': "Applicable only to eCheck.Net. The value submitted for bank account name does not contain valid characters."},
116: {'response_code': 3, 'reason_code': 116, 'text': "The authentication indicator is invalid.", 'details': "This error is only applicable to Verified by Visa and MasterCard SecureCode transactions. The ECI value for a Visa transaction; or the UCAF indicator for a MasterCard transaction submitted in the x_authentication_indicator field is invalid."},
117: {'response_code': 3, 'reason_code': 117, 'text': "The cardholder authentication value is invalid.", 'details': "This error is only applicable to Verified by Visa and MasterCard SecureCode transactions. The CAVV for a Visa transaction; or the AVV/UCAF for a MasterCard transaction is invalid."},
118: {
    'response_code': 3, 
    'reason_code': 118, 
    'text': "The combination of authentication indicator and cardholder authentication value is invalid.", 
    'details': "This error is only applicable to Verified by Visa and MasterCard SecureCode transactions. The combination of authentication indicator and cardholder authentication value for a Visa or MasterCard transaction is invalid. For more information, see the \"Cardholder Authentication\” topic."},
119: {'response_code': 3, 'reason_code': 119, 'text': "Transactions having cardholder authentication values cannot be marked as recurring.", 'details': "This error is only applicable to Verified by Visa and MasterCard SecureCode transactions. Transactions submitted with a value in x_authentication_indicator and x_recurring_billing=YES will be rejected."},
120: {'response_code': 3, 'reason_code': 120, 'text': "An error occurred during processing. Please try again.", 'details': "The system-generated void for the original timed-out transaction failed. (The original transaction timed out while waiting for a response from the authorizer.)"},
121: {'response_code': 3, 'reason_code': 121, 'text': "An error occurred during processing. Please try again.", 'details': "The system-generated void for the original errored transaction failed. (The original transaction experienced a database error.)"},
122: {'response_code': 3, 'reason_code': 122, 'text': "An error occurred during processing. Please try again.", 'details': "The system-generated void for the original errored transaction failed. (The original transaction experienced a processing error.)"},
123: {'response_code': 3, 'reason_code': 123, 'text': "This account has not been given the permission(s) required for this request.", 'details': "The transaction request must include the API Login ID associated with the payment gateway account."},
127: {'response_code': 2, 'reason_code': 127, 'text': "The transaction resulted in an AVS mismatch. The address provided does not match billing address of cardholder.", 'details': "The system-generated void for the original AVS-rejected transaction failed."},
128: {'response_code': 3, 'reason_code': 128, 'text': "This transaction cannot be processed.", 'details': "The customers financial institution does not currently allow transactions for this account."},
130: {'response_code': 3, 'reason_code': 130, 'text': "This payment gateway account has been closed.", 'details': "IFT: The payment gateway account status is Blacklisted."},
131: {'response_code': 3, 'reason_code': 131, 'text': "This transaction cannot be accepted at this time.", 'details': "IFT: The payment gateway account status is Suspended-STA."},
132: {'response_code': 3, 'reason_code': 132, 'text': "This transaction cannot be accepted at this time.", 'details': "IFT: The payment gateway account status is Suspended-Blacklist."},
141: {'response_code': 2, 'reason_code': 141, 'text': "This transaction has been declined.", 'details': "The system-generated void for the original FraudScreen-rejected transaction failed."},
145: {'response_code': 2, 'reason_code': 145, 'text': "This transaction has been declined.", 'details': "The system-generated void for the original card code-rejected and AVS-rejected transaction failed."},
152: {'response_code': 3, 'reason_code': 152, 'text': "The transaction was authorized, but the client could not be notified; the transaction will not be settled.", 'details': "The system-generated void for the original transaction failed. The response for the original transaction could not be communicated to the client."},
165: {'response_code': 2, 'reason_code': 165, 'text': "This transaction has been declined.", 'details': "The system-generated void for the original card code-rejected transaction failed."},
170: {'response_code': 3, 'reason_code': 170, 'text': "An error occurred during processing. Please contact the merchant.", 'details': "Concord EFS Provisioning at the processor has not been completed."},
171: {'response_code': 2, 'reason_code': 171, 'text': "An error occurred during processing. Please contact the merchant.", 'details': "Concord EFS This request is invalid."},
172: {'response_code': 2, 'reason_code': 172, 'text': "An error occurred during processing. Please contact the merchant.", 'details': "Concord EFS The store ID is invalid."},
173: {'response_code': 3, 'reason_code': 173, 'text': "An error occurred during processing. Please contact the merchant.", 'details': "Concord EFS The store key is invalid."},
174: {'response_code': 2, 'reason_code': 174, 'text': "The transaction type is invalid. Please contact the merchant.", 'details': "Concord EFS This transaction type is not accepted by the processor."},
175: {'response_code': 3, 'reason_code': 175, 'text': "The processor does not allow voiding of credits.", 'details': "Concord EFS This transaction is not allowed. The Concord EFS processing platform does not support voiding credit transactions. Please debit the credit card instead of voiding the credit."},
180: {'response_code': 3, 'reason_code': 180, 'text': "An error occurred during processing. Please try again.", 'details': "The processor response format is invalid."},
181: {'response_code': 3, 'reason_code': 181, 'text': "An error occurred during processing. Please try again.", 'details': "The system-generated void for the original invalid transaction failed. (The original transaction included an invalid processor response format.)"},
185: {'response_code': 3, 'reason_code': 185, 'text': "This reason code is reserved or not applicable to this API.", 'details': " "},
193: {'response_code': 4, 'reason_code': 193, 'text': "The transaction is currently under review.", 'details': "The transaction was placed under review by the risk management system."},
200: {'response_code': 2, 'reason_code': 200, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The credit card number is invalid."},
201: {'response_code': 2, 'reason_code': 201, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The expiration date is invalid."},
202: {'response_code': 2, 'reason_code': 202, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The transaction type is invalid."},
203: {'response_code': 2, 'reason_code': 203, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The value submitted in the amount field is invalid."},
204: {'response_code': 2, 'reason_code': 204, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The department code is invalid."},
205: {'response_code': 2, 'reason_code': 205, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The value submitted in the merchant number field is invalid."},
206: {'response_code': 2, 'reason_code': 206, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The merchant is not on file."},
207: {'response_code': 2, 'reason_code': 207, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The merchant account is closed."},
208: {'response_code': 2, 'reason_code': 208, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The merchant is not on file."},
209: {'response_code': 2, 'reason_code': 209, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. Communication with the processor could not be established."},
210: {'response_code': 2, 'reason_code': 210, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The merchant type is incorrect."},
211: {'response_code': 2, 'reason_code': 211, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The cardholder is not on file."},
212: {'response_code': 2, 'reason_code': 212, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The bank configuration is not on file"},
213: {'response_code': 2, 'reason_code': 213, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The merchant assessment code is incorrect."},
214: {'response_code': 2, 'reason_code': 214, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. This function is currently unavailable."},
215: {'response_code': 2, 'reason_code': 215, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The encrypted PIN field format is invalid."},
216: {'response_code': 2, 'reason_code': 216, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The ATM term ID is invalid."},
217: {'response_code': 2, 'reason_code': 217, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. This transaction experienced a general message format problem."},
218: {'response_code': 2, 'reason_code': 218, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The PIN block format or PIN availability value is invalid."},
219: {'response_code': 2, 'reason_code': 219, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The ETC void is unmatched."},
220: {'response_code': 2, 'reason_code': 220, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The primary CPU is not available."},
221: {'response_code': 2, 'reason_code': 221, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. The SE number is invalid."},
222: {'response_code': 2, 'reason_code': 222, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. Duplicate auth request (from INAS)."},
223: {'response_code': 2, 'reason_code': 223, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. This transaction experienced an unspecified error."},
224: {'response_code': 2, 'reason_code': 224, 'text': "This transaction has been declined.", 'details': "This error code applies only to merchants on FDC Omaha. Please re-enter the transaction."},
243: {'response_code': 3, 'reason_code': 243, 'text': "Recurring billing is not allowed for this eCheck.Net type.", 'details': "The combination of values submitted for x_recurring_billing and x_echeck_type is not allowed."},
244: {'response_code': 3, 'reason_code': 244, 'text': "This eCheck.Net type is not allowed for this Bank Account Type.", 'details': "The combination of values submitted for x_bank_acct_type and x_echeck_type is not allowed."},
245: {'response_code': 3, 'reason_code': 245, 'text': "This eCheck.Net type is not allowed when using the payment gateway hosted payment form.", 'details': "The value submitted for x_echeck_type is not allowed when using the payment gateway hosted payment form."},
246: {'response_code': 3, 'reason_code': 246, 'text': "This eCheck.Net type is not allowed.", 'details': "The merchants payment gateway account is not enabled to submit the eCheck.Net type."},
247: {'response_code': 3, 'reason_code': 247, 'text': "This eCheck.Net type is not allowed.", 'details': "The combination of values submitted for x_type and x_echeck_type is not allowed."},
250: {'response_code': 2, 'reason_code': 250, 'text': "This transaction has been declined.", 'details': "This transaction was submitted from a blocked IP address."},
251: {'response_code': 2, 'reason_code': 251, 'text': "This transaction has been declined.", 'details': "The transaction was declined as a result of triggering a Fraud Detection Suite filter."},
252: {'response_code': 4, 'reason_code': 252, 'text': "Your order has been received. Thank you for your business!", 'details': "The transaction was accepted, but is being held for merchant review. The merchant may customize the customer response in the Merchant Interface."},
253: {'response_code': 4, 'reason_code': 253, 'text': "Your order has been received. Thank you for your business!", 'details': "The transaction was accepted and was authorized, but is being held for merchant review. The merchant may customize the customer response in the Merchant Interface."},
254: {'response_code': 2, 'reason_code': 254, 'text': "Your transaction has been declined.", 'details': "The transaction was declined after manual review."},
261: {'response_code': 3, 'reason_code': 261, 'text': "An error occurred during processing. Please try again.", 'details': "The transaction experienced an error during sensitive data encryption and was not processed. Please try again."},
270: {'response_code': 3, 'reason_code': 270, 'text': "The line item [item number] is invalid.", 'details': "A value submitted in x_line_item for the item referenced is invalid."},
271: {'response_code': 3, 'reason_code': 271, 'text': "The number of line items submitted is not allowed. A maximum of 30 line items can be submitted.", 'details': "The number of line items submitted exceeds the allowed maximum of 30."},
271: {'response_code': 3, 'reason_code': 271, 'text': "The number of line items submitted is not allowed. A maximum of 30 line items can be submitted.", 'details': "The number of line items submitted exceeds the allowed maximum of 30."},
288: {'response_code': 3, 'reason_code': 288, 'text': "Merchant is not registered as a Cardholder Authentication participant. This transaction cannot be accepted.", 'details': "The merchant has not indicated participation in any Cardholder Authentication Programs in the Merchant Interface."},
289: {'response_code': 3, 'reason_code': 289, 'text': "This processor does not accept zero dollar authorization for this card type.", 'details': "Your credit card processing service does not yet accept zero dollar authorizations for Visa credit cards. You can find your credit card processor listed on your merchant profile."},
290: {'response_code': 3, 'reason_code': 290, 'text': "One or more required AVS values for zero dollar authorization were not submitted.", 'details': "When submitting authorization requests for Visa, the address and zip code fields must be entered."},
295: {'response_code': 4, 'reason_code': 295, 'text': "The amount of this request was only partially approved on the given prepaid card. Additional payments are required to complete the balance of this transaction.", 'details': "The merchant must have partial authorization enabled in the merchant interface in order to receive this error."},
296: {'response_code': 3, 'reason_code': 296, 'text': "The specified SplitTenderId is not valid", 'details': " "},
297: {'response_code': 3, 'reason_code': 297, 'text': "A transaction ID and a split tender ID cannot both be used in a single transaction request.", 'details': " "},
300: {'response_code': 3, 'reason_code': 300, 'text': "The device ID is invalid.", 'details': "Invalid x_device_id value"},
301: {'response_code': 3, 'reason_code': 301, 'text': "The device batch ID is invalid.", 'details': "Invalid x_device_batch_id value"},
302: {'response_code': 3, 'reason_code': 302, 'text': "The reversal flag is invalid.", 'details': "Invalid x_reversal value"},
303: {'response_code': 3, 'reason_code': 303, 'text': "The device batch is full. Please close the batch.", 'details': "The current device batch must be closed manually from the POS device."},
304: {'response_code': 3, 'reason_code': 304, 'text': "The original transaction is in a closed batch.", 'details': "The original transaction has been settled and cannot be reversed."},
305: {'response_code': 3, 'reason_code': 305, 'text': "The merchant is configured for auto-close.", 'details': "This merchant is configured for auto-close and cannot manually close batches."},
306: {'response_code': 3, 'reason_code': 306, 'text': "The batch is already closed.", 'details': "The batch is already closed."},
307: {'response_code': 1, 'reason_code': 307, 'text': "The reversal was processed successfully.", 'details': "The reversal was processed successfully."},
308: {'response_code': 1, 'reason_code': 308, 'text': "Original transaction for reversal not found.", 'details': "The transaction submitted for reversal was not found."},
309: {'response_code': 3, 'reason_code': 309, 'text': "The device has been disabled.", 'details': "The device has been disabled."},
310: {'response_code': 1, 'reason_code': 310, 'text': "This transaction has already been voided.", 'details': "This transaction has already been voided."},
311: {'response_code': 1, 'reason_code': 311, 'text': "This transaction has already been captured", 'details': "This transaction has already been captured."},
315: {'response_code': 2, 'reason_code': 315, 'text': "The credit card number is invalid.", 'details': "This is a processor-issued decline."},
316: {'response_code': 2, 'reason_code': 316, 'text': "The credit card expiration date is invalid.", 'details': "This is a processor-issued decline."},
317: {'response_code': 2, 'reason_code': 317, 'text': "The credit card has expired.", 'details': "This is a processor-issued decline."},
318: {'response_code': 2, 'reason_code': 318, 'text': "A duplicate transaction has been submitted.", 'details': "This is a processor-issued decline."},
319: {'response_code': 2, 'reason_code': 319, 'text': "The transaction cannot be found.", 'details': "This is a processor-issued decline."},
}
